Fix rate-limiting issue in CodeCommit
Whitehall has over 9000 tags, but AWS CodeCommit has a push limit
of 4,000 reference updates:

https://docs.aws.amazon.com/codecommit/latest/userguide/troubleshooting-git.html#:~:text=The%20maximum%20number%20of%20reference%20updates%20per%20push%20is%204%2C000

I've now configured it to only push the 4000 latest tags.

Note: I did also have to remove this line:
`${git} push ${aws_remote} +refs/tags/*:refs/tags/*`

It was causing the same error (in Whitehall, at least):

```
UnrecognizedFormatException: Too many reference update commands
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
```

Pushing `refs/tags` seems redundant as we're already pushing
tags on line 57.